### ISSUE TITLE
SSLv3 methods disabled

### ISSUE THREAD

**Issue by boehm-e** [kyungw00k/node-ping-proxy#3]
including this module make my program crash with the following error : 

_tls_common.js:23
      this.context.init(secureProtocol);
                   ^

Error: SSLv3 methods disabled
    at Error (native)
    at new SecureContext (_tls_common.js:23:20)
    at Object.createSecureContext (_tls_common.js:42:11)
    at Object.exports.connect (_tls_wrap.js:955:21)
    at Agent.createConnection (https.js:73:22)
    at Agent.createSocket (_http_agent.js:174:16)
    at Agent.addRequest (_http_agent.js:143:23)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)

**Comment by kyungw00k** [comment]
@boehm-e  See https://github.com/tschwecke/harvey/issues/79

**Comment by boehm-e** [comment]
@kyungw00k Thank you for the reply.
